version: "3.5"

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  src:
    build:
      context: src/
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    links:
      - api
    depends_on:
      - api

  api:
    build:
      context: api/
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=commando
    #   - POSTGRES_PASSWORD=example
